### ISSUE TITLE
rbenv not installed or found in failing cap deploy

### ISSUE THREAD

**Issue by psnider30** [capistrano/rbenv#101]
Hi, `bundle exec cap staging deploy` is failing after upgrading ruby from 2.6.6 to 2.6.9. 
This app is in production, so it would be great to get help getting this deploy fixed! Thank you!

Here's the details:

Error from CircleCI:
```
00:00 [0;34;49mrbenv:validate[0m
      [0;33;49mWARN[0m  rbenv: 2.6.9 is not installed or not found in $HOME/.rbenv/versions/2.6.9 on 3.218.169.146
```
![Screenshot 2023-10-10 at 3 41 49 PM](https://github.com/capistrano/rbenv/assets/13356541/8504b725-94a1-4768-8daa-953c9b0f2a2b)

Here are our gem versions:

`group :development do
    gem "capistrano", "~> 3.10", require: false
    gem "capistrano-rails", "~> 1.6", require: false
    gem 'capistrano-rbenv', '~> 2.2'
end`

`set :rbenv_ruby, '2.6.9'` is called in the `Capfile`. 
I'm also calling `set :rbenv_ruby, '2.6.9'` in `deploy.rb` due to the deploy failing. (although it should already be included).
The ruby version is also defined in `.ruby-version` and the `Gemfile`.
We are using this docker image:  `circleci/ruby:2.6.9-node-browsers`. The previous image was `circleci/ruby:2.6.6-node-browsers`.

Our configuration worked for ruby 2.6.6, but now has this error for ruby 2.6.9. I've attached the `Capfile` and `deploy.rb` as .txt files.
Any help you can provide to get this deploy running would be greatly appreciated! 

[Capfile.txt](https://github.com/capistrano/rbenv/files/12862712/Capfile.txt)
[modiifed_deploy.txt](https://github.com/capistrano/rbenv/files/12862713/modiifed_deploy.txt)

**Comment by mattbrictson** [comment]
`rbenv_ruby` is the version of Ruby you want to use on the remote servers. In this case, since you are running `cap staging deploy`, it is the staging server(s). Have you upgraded your staging server(s) to Ruby 2.6.9? Specifically, server `3.218.169.146` according to the error message.

This is something you'll need to do manually. Capistrano-rbenv does not install Ruby.

**Comment by psnider30** [comment]
Yes, nice catch! I hadn't done the manual upgrade yet, so that solved the issue. Thank you!
