### ISSUE TITLE
rbenv_map_bins not set

### ISSUE THREAD

**Issue by ghost** [capistrano/rbenv#13]
I keep getting the follow error. Tried to debug but I'm stuck.

undefined method `include?' for nil:NilClass
/Users/matbox/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rbenv-362dbc02ef96/lib/capistrano/tasks/rbenv.rake:6:in`block in <top (required)>'
...

Looks like for some reason rbenv_map_bins is not set (OS Mavericks). How can that happen?

My environment:

$ rbenv -v
rbenv 0.4.0-74-g95a039a

$ which ruby
/Users/matbox/.rbenv/shims/ruby

$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.0.0]

Some relevant lines from my Gemfile:

require 'capistrano/rbenv'
require 'capistrano/bundler'
require 'capistrano/rails/assets'

set :rbenv_type, :user
set :rbenv_ruby, '2.0.0p-247'

**Comment by hiveer** [comment]
@kirs It works, but I don't know why. I saw this command line
`set :rbenv_map_bins, %w{rake gem bundle ruby}` is already defined in `: defaults` task. 
Why we need to set it explicitly? And what does it actually do. 

thanks
