### ISSUE TITLE
Allow stages to opt out of rbenv tasks

### ISSUE THREAD

**Issue by jimmycuadra** [capistrano/rbenv#31]
I have a stage which runs against an environment that will not have rbenv installed. Currently, the capistrano-rbenv tasks are being applied to all stages via `Capistrano::DSL.stages`.

In an attempt to get around this, I created a special role that is only used on my non-rbenv stage, and set `:rbenv_roles` to exclude it. However, because of capistrano/capistrano#740, even when no host matches, the blocks passed to `on` in the rbenv Cap tasks still execute, causing my entire Cap run to fail when `exit 1` happens.

While the proper fix, IMO, is for the issue in Capistrano to get fixed, capistrano-rbenv could provide a workaround by allowing stages to opt out of having the rbenv tasks added to its run.

Because capistrano-rbenv is not really verifying that rbenv is installed, and is simply checking for the existence of `:rbenv_ruby_dir`, it's possible to trick the task into thinking it's installed by setting `:rbenv_ruby_dir` to something like `/`. This is a pretty bad hack, and quite unintuitive, so I still think a clearer mechanism to opt out is warranted.

Thanks for your time!

**Comment by elthariel** [comment]
I've a somewhat related problem, that I think should be taken into account if someone decide to work on this.

I'm using capistrano-db-tasks, which uses run_locally to grab some configuration from rails. I don't have the same setup locally (~/.rbenv) than on my remote machine (/opt/rbenv/...), which makes the task fails.

**Comment by will-in-wi** [comment]
This ticket has a workaround, so I'm going to close.

@elthariel: your issue is different, so if you would still like it addressed, please open a new ticket.

Thanks!
