### ISSUE TITLE
rbenv vars support

### ISSUE THREAD

**Issue by blackjid** [capistrano/rbenv#41]
Hi, I have created a few tasks to manage environmental variables with `rbenv-vars` plugin.

I'm willing to create PR with them if it makes sense to add this kind of features.

Probably it would be a good idea to add them separated from the core rbenv features. That way it will be optional to add them.

```ruby
require 'capistrano/rbenv'
require 'capistrano/rbenv/vars'
```

I have a this tasks
```ruby
cap rbenv:vars:add[key,value]      # Add environmental variable
cap rbenv:vars:remove[key]         # Remove environmental variable
cap rbenv:vars:show                # Show current environmental variables
```

**Comment by jamesfzhang** [comment]
@blackjid Can you share your tasks for updating rbenv vars?

**Comment by blackjid** [comment]
of course! wow, how can one forgott completely about an issue... I didn't even remember having read all those replies!

here they are, they served well our team :)
https://github.com/platanus/negroku/blob/master/lib/negroku/capistrano/tasks/rbenv.rake

**Comment by blackjid** [comment]
I'm going to close the issue since I don't use capistrano anymore, feel free to reopen if someone wants to continue de discussion.
