### ISSUE TITLE
.ruby-version support

### ISSUE THREAD

**Issue by blackjid** [capistrano/rbenv#5]
Hey, I'm trying to use cap v3, with capistrano-rbenv but I get "rbenv: rbenv_ruby is not set"  

I haven't set the rbenv_ruby variable because I already have a .ruby-version  file in my proyect that define the ruby version. So I don't want to repeat that information in two locations.

Does capistrano-rbenv supports .ruby-version files to get the version in any wat? 

Does it make any sense?? If it doesn't support and it make sense I can to make a PR providing that functionality….. 

thanks!

**Comment by codyrobbins** [comment]
Is there any particular reason that the gem itself is not trying to read `.ruby-version` itself as a default unless specifically overridden? It seems like ninety-nine percent of projects are going to have a `.ruby-version` in which case having to put a magic incantation (`set :rbenv_ruby, File.read('.ruby-version').strip`) in every Capistrano configuration is backwards.

I’m happy to make a pull request for this but wanted to make sure there’s not a specific reason the gem isn’t doing it.

**Comment by kirs** [comment]
@codyrobbins you can read the particular reason in my comment above.
