### ISSUE TITLE
Rbenv update & setup tasks

### ISSUE THREAD

**Issue by pcrum** [capistrano/rbenv#51]
Hello,

In Capistrano 2.x, there was an ability to run  cap [environment] rbenv:update and cap [environment] rbenv:setup. Are these tasks looking to be added back in?

**Comment by will-in-wi** [comment]
It doesn't look like there are such plans. What's the use case to do so?

**Comment by will-in-wi** [comment]
Given the age of this ticket, I'm closing. Feel free to reopen if needed.
