### ISSUE TITLE
rbenv:validate fails erroneously

### ISSUE THREAD

**Issue by jkarnesPerfectCube** [capistrano/rbenv#72]
I am trying to run a `cap staging deploy` with `capistrano/rbenv` and `capistrano/bundler`. I know for a fact that rbenv is correctly installed at the location being queried. I am only running the verification task on pc-app-1 as `dev` (our deploy user)
Here's some output:

**Issuing the rbenv:validate command**
```
justin@jkarnes-pcube:~/Projects/PerfectCube/PC$ cap staging rbenv:validate
00:00 rbenv:validate
      rbenv: 2.3.4 is not installed or not found in /home/dev/.rbenv/versions/2.3.4

```

**Verifying rbenv 2.3.4 existence**
```
dev@pc-app-1:~$ ls ~/.rbenv/versions
2.3.4
dev@pc-app-1:~$ ls /home/dev/.rbenv/versions # being explicit
2.3.4
```

**Configuration relevant to the library**

```
set :rbenv_type, :user
set :rbenv_ruby, '2.3.4'
set :rbenv_custom_path, "/home/dev/.rbenv" # removing this does nothing to solve the issue
set :rbenv_prefix, "RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)}
 {fetch(:rbenv_path)}/bin/rbenv exec"
```
Development machine and Local machine are both Ubuntu 16.04

If you need anything else or additional output, please let me know and I will work with you in solving this issue.

**Comment by ivanovaleksey** [comment]
Hi @jkarnesPerfectCube, I have tried to `rbenv:validate` myself and everything works fine.
I have looked through the task's code and I don't understand why it doesn't work for you.

I would recommend you to debug the task itself locally. You can open the gem on your developer machine and do some `puts`ing (I would use this way if it wouldn't work for me).

**Comment by jkarnesPerfectCube** [comment]
After tracing the path and looking at the task as defined in the library I have traced the validate "failure" to running on a machine which does not have rbenv installed on it. We have a web server which compiles static assets through webpack and nodeJS instead of the rails asset system so it is included as a release role to hit a custom task and to get repository code from GitHub (I include this information since there was a previous issue request which had a similar issue with the question as to "why is it even in there?").

I would strongly suggest implementing one of the following:

1. Better failure output. Receiving "this task failed" but not knowing on which machines is unhelpful... especially if you don't know the task is running on all release roles
2. Ability to specify or customize which roles get hit by `rbenv:validate`. I don't feel like this would be too difficult since roles can already have `:no_release => true`.

Thank you for your swift response and your work on this gem! It is invaluable once working.
