### ISSUE TITLE
ruby is not installed or not found

### ISSUE THREAD

**Issue by ktimothy** [capistrano/rbenv#79]
The message:
```
00:00 rbenv:validate
      WARN  rbenv: 2.5.1
 is not installed or not found in $HOME/.rbenv/versions/2.5.1
```

```ruby
set :rbenv_type, :user # or :system, depends on your rbenv setup
set :rbenv_ruby, `cat .ruby-version`
```

the directory exists:
```
$ ls $HOME/.rbenv/versions/2.5.1
bin  include  lib  share
```

capistrano 3.11.0, capistrano-rbenv 2.3.1

What may be the problem with it?

**Comment by ktimothy** [comment]
LOOOOL, actually, I have found the problem :D

`set :rbenv_ruby, \`cat .ruby-version\`` adds a newline to rbenv_ruby, which then leads to wrong generated test command `[-d $HOME/.rbenv/versions/2.5.1; ]` (note the semicolon).

**Comment by mattbrictson** [comment]
Good catch! You can get rid of that newline with `chomp`, like this:

```ruby
set :rbenv_ruby, `cat .ruby-version`.chomp
```

Glad to hear you figured it out!
