### ISSUE TITLE
Licence missing in the rubygems version and in the gemspec

### ISSUE THREAD

**Issue by mensfeld** [capistrano/rbenv#81]
The "capistrano-rbenv" gem seems not to have a license at all. Unless a license that specifies otherwise is included, nobody else can use, copy, distribute, or modify that library without being at risk of take-downs, shake-downs, or litigation.

I know, that this gem has a license on github, however it's missing one at rubygems and in a gemspec.

![zrzut ekranu z 2018-09-03 11-07-32](https://user-images.githubusercontent.com/392754/44977880-9588d680-af69-11e8-9d83-af4f801a8fe1.png)

**Comment by mattbrictson** [comment]
The fix will take effect the next time the gem is released. I'll do that within a week.

**Comment by mattbrictson** [comment]
2.1.4 released: https://rubygems.org/gems/capistrano-rbenv/versions/2.1.4
