### ISSUE TITLE
bash: /home/myuser/.rbenv/bin/rbenv: No such file or directory when production deploying

### ISSUE THREAD

**Issue by cratag** [capistrano/rbenv#96]
```
 bundler:config
      01 $HOME/.rbenv/bin/rbenv exec bundle config --local deployment true
      01 bash: /home/ers/.rbenv/bin/rbenv: No such file or directory
```

Terminal logs `/home/MYUSER/.rbenv/bin/rbenv: No such file or directory` which is true:

```
ls /home/ers/.rbenv
plugins  shims  version  versions
```

I don't have a bin/rbenv folder. I believe it should be somewhere else, but running rbenv doctor shows:

```
~/.rbenv# curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /home/ers/.rbenv/plugins/ruby-build/bin/rbenv-install (ruby-build 20210423)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

but `cd /usr/bin/rbenv` is unreachable. I can go to `/usr/bin` and when I `ls -al`, I'm able to see rbenv folder in a specific way:

`lrwxrwxrwx  1 root   root          26 May  1  2017  rbenv -> ../lib/rbenv/libexec/rbenv`

and I can't find that `../lib/` folder

**Comment by brendon** [comment]
Did you manage to figure it out?

**Comment by cratag** [comment]
Yes. I can't exactly remember where, but you must find a bin/even folder
somewhere and change the Capistrano rbenv path pointing there.

There's a line you have to add to specify the rbenv path somewhere in the
docs. And you have to search the bin/rbenv folder.

Rbenv doctor should tell you where the rbenv path is.

**Comment by brendon** [comment]
Thanks @cratag, I figured that might be the case. Strange that it's misconfigured from the start? Did rbenv change and remove the root `bin` directory?

**Comment by cratag** [comment]
Possibly. It was quite strange. Let me know if you're able to do it
yourself

**Comment by brendon** [comment]
In my case I used the ubuntu `rbenv` package. I had to set the following as the `bin` is stored away from the userspace ruby installs:

```
set :rbenv_prefix, '/usr/bin/rbenv exec'
```

**Comment by arifikhsan** [comment]
> In my case I used the ubuntu `rbenv` package. I had to set the following as the `bin` is stored away from the userspace ruby installs:
> 
> ```
> set :rbenv_prefix, '/usr/bin/rbenv exec'
> ```

this is saved my life

**Comment by Flinsch** [comment]
> In my case I used the ubuntu `rbenv` package. I had to set the following as the `bin` is stored away from the userspace ruby installs:
> 
> ```
> set :rbenv_prefix, '/usr/bin/rbenv exec'
> ```

This fixed it for me also (Ubuntu with Plesk). Thanks a lot!
