### ISSUE TITLE
Exception while executing: if test ! -d \$HOME/.rbenv/plugins/ruby-build; then echo "Directory does not exist '\$HOME/.rbenv/plugins/ruby-build'" 1>&2; false; fi exit status

### ISSUE THREAD

**Issue by keithslater** [capistrano/rbenv#98]
We are trying to upgrade to Ruby 3 and Rails 6.1. Currently everything works fine with Ruby 2.5.3 and Rails 5.2. When trying to deploy the new upgrade we're getting this error:
```
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as ec2-user@: Exception while executing as ec2-user@: if test ! -d \\$HOME/.rbenv/plugins/ruby-build; then echo "Directory does not exist '\\$HOME/.rbenv/plugins/ruby-build'" 1>&2; false; fi exit status: 1 (SSHKit::Runner::ExecuteError)
Exception while executing: if test ! -d \$HOME/.rbenv/plugins/ruby-build; then echo "Directory does not exist '\$HOME/.rbenv/plugins/ruby-build'" 1>&2; false; fi exit status
```

With our upgrade no versions of capistrano or rbenv has changed. Here are our versions:

```
    capistrano (3.16.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (2.0.1)
      capistrano (~> 3.1)
    capistrano-rails (1.6.1)
      capistrano (~> 3.1)
      capistrano-bundler (>= 1.1, < 3)
    capistrano-rbenv (2.2.0)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    capistrano-rbenv-install (1.2.0)
      capistrano (>= 3.0)
      capistrano-rbenv (>= 2.0)
    capistrano-sidekiq (1.0.3)
      capistrano (>= 3.9.0)
      sidekiq (>= 3.4, < 6.0)
    capistrano-upload-config (0.8.2)
      capistrano (>= 3.0)
    capistrano3-puma (3.1.1)
      capistrano (~> 3.7)
      capistrano-bundler
```

If I change back and try to deploy ruby 2.5.3 and rails 5.2 everything works fine. All of the gems above are the same in both. The directory `$HOME/.rbenv/plugins/ruby-build` definitely exists either way.

We have the following defined:
```
set :rbenv_type, :user
set :rbenv_ruby, ruby_version_from_repo
set :rbenv_prefix, "RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)} #{fetch(:rbenv_path)}/bin/rbenv exec"
set :rbenv_map_bins, %w{rake gem bundle ruby rails sidekiq sidekiqctl puma pumactl}
set :rbenv_roles, :all # default value
```

Does rbenv work with Ruby 3 and Rails 6.1? Or am I missing something else here? I've noticed this repo hasn't been updated ina. while, should we look for an alternative solution?

**Comment by mattbrictson** [comment]
In the error message I see there is a backslash before `$HOME` in the shell script that is being run:

```
if test ! -d \$HOME/.rbenv/plugins/ruby-build; ...
```

Likely that is the cause of the error. The shell is looking for the literal `$HOME` path instead of expanding the variable.

This was discussed in #88. Unfortunately, the fix caused other problems and had to be reverted.

I think the workaround is to use `~` instead of `$HOME`. Can you try that? Something like this:

```ruby
set :rbenv_path, "~/.rbenv"
```

**Comment by mattbrictson** [comment]
Also, my guess is that the escaping behavior changed in sshkit at some point, and that is why your upgrade caused this error to appear. Can you check if the sshkit version changed pre- and post-upgrade?

**Comment by keithslater** [comment]
Ah yeah I did look at sshkit but running 1.21.2 on both.

I set `rbenv_path` (with full path) and that did solve it, thanks. I did see that other thread but I think I got confused between rbenv_prefix and rbenv_path. This workaround should be fine for us. Thanks again

**Comment by ddoherty03** [comment]
Shouldn't you change line 43 to '~/.rbenv' to fix this before closing it?  I got bit by this too without any setting for rbenv_path.
